export default {
  id: 56139,
  url: 'https://www.tvmaze.com/shows/56139/meta-runner',
  name: 'Meta Runner',
  type: 'Animation',
  language: 'English',
  genres: ['Action', 'Adventure'],
  status: 'Running',
  runtime: 15,
  averageRuntime: 15,
  premiered: '2019-07-25',
  ended: null,
  officialSite: 'https://youtube.com/channel/UCn_FAXem2-e3HQvmK-mOH4g',
  schedule: { time: '', days: ['Friday'] },
  rating: { average: 5.5 },
  weight: 51,
  network: null,
  webChannel: {
    id: 21,
    name: 'YouTube',
    country: null,
    officialSite: 'https://www.youtube.com',
  },
  dvdCountry: null,
  externals: { tvrage: null, thetvdb: 367418, imdb: 'tt10695770' },
  image: null,
  summary:
    '<p><b>Meta Runner</b> is an Australian computer animated web television series created and developed by Glitch Productions</p>',
  updated: 1658668666,
  _links: {
    self: { href: 'https://api.tvmaze.com/shows/56139' },
    previousepisode: { href: 'https://api.tvmaze.com/episodes/2354249' },
    nextepisode: { href: 'https://api.tvmaze.com/episodes/2354250' },
  },
}
